import { router, json, error } from '@appdeploy/sdk';
import { storage } from '@appdeploy/sdk';
const safeId=(id:string)=>id.replace(/[^a-zA-Z0-9_-]/g,'').slice(0,40);
const imagePath=(id:string,index:number)=>`portfolio/${safeId(id)}/${String(index).padStart(2,'0')}.webp`;
const listPaths=async(id:string)=>{const {paths}=await storage.list({prefix:`portfolio/${safeId(id)}/`,limit:20});return paths.sort()};
const toUrls=async(paths:string[])=>{const urls=await storage.url(paths);return urls.map(x=>x.url)}; const cleanupAlways=async()=>{const marker='portfolio/_migrations/remove-always-v1.done';const [state]=await storage.read([marker]);if(state.content!==null)return;const paths=await listPaths('02');if(paths.length>1){const deleted=await storage.delete([paths[1]]);if(deleted[0]){const remaining=await listPaths('02');for(let i=0;i<remaining.length;i++){const old=remaining[i];const next=imagePath('02',i);if(old===next)continue;const [file]=await storage.read([old]);if(file.content!==null){const ok=await storage.write([{path:next,content:file.content,contentType:'image/webp'}]);if(ok[0])await storage.delete([old])}}}}await storage.write([{path:marker,content:'done',contentType:'text/plain'}])};
export const handler=router({
  'GET /api/_healthcheck':[async()=>json({message:'Success'})],
  'GET /api/project-images/:id':[async({params})=>{if(safeId(params.id)==='02')await cleanupAlways();return json({images:await toUrls(await listPaths(params.id))})}],
  'POST /api/project-images/:id':[async({params,body})=>{const id=safeId(params.id);const payload=body as {images?:Array<{content:string;contentType:string}>};if(!payload.images?.length)return error('No images supplied',400);const existing=await listPaths(id);if(existing.length+payload.images.length>8)return error('Maximum 8 images per project',400);const items=payload.images.map((img,i)=>({path:imagePath(id,existing.length+i),content:img.content,contentType:img.contentType||'image/webp'}));const results=await storage.write(items);if(results.some(ok=>!ok))return error('Some images could not be stored',500);return json({images:await toUrls(await listPaths(id))})}],
  'DELETE /api/project-images/:id':[async({params,body})=>{const id=safeId(params.id);const payload=body as {indices?:number[]};const paths=await listPaths(id);const indices=Array.from(new Set((payload.indices||[]).filter(i=>Number.isInteger(i)&&i>=0&&i<paths.length))).sort((a,b)=>b-a);if(!indices.length)return error('No images selected',400);const deleted=await storage.delete(indices.map(i=>paths[i]));if(deleted.some(ok=>!ok))return error('Some images could not be deleted',500);const remaining=await listPaths(id);for(let i=0;i<remaining.length;i++){const old=remaining[i];const next=imagePath(id,i);if(old===next)continue;const [file]=await storage.read([old]);if(file.content===null)continue;const ok=await storage.write([{path:next,content:file.content,contentType:'image/webp'}]);if(!ok[0])return error('Could not reorganize gallery',500);await storage.delete([old]);}return json({images:await toUrls(await listPaths(id))})}],
  'PUT /api/project-images/:id':[async({params,body})=>{const id=safeId(params.id);const payload=body as {indices?:number[];images?:Array<{content:string;contentType:string}>};const paths=await listPaths(id);const indices=Array.from(new Set((payload.indices||[]).filter(i=>Number.isInteger(i)&&i>=0&&i<paths.length))).sort((a,b)=>a-b);if(!indices.length||!payload.images?.length||indices.length!==payload.images.length)return error('Select the same number of images to replace',400);for(let n=0;n<indices.length;n++){const written=await storage.write([{path:imagePath(id,indices[n]),content:payload.images[n].content,contentType:payload.images[n].contentType||'image/webp'}]);if(!written[0])return error('Could not store replacement image',500)}return json({images:await toUrls(await listPaths(id))})}],
});
